### ISSUE TITLE
scale on mobile devices

### ISSUE THREAD

**Issue by kimasendorf** [mattdesl/canvas-loop#2]
I wonder how to use the scale property!?

In the examples you use it like

```
var app = createLoop(canvas, {
  scale: window.devicePixelRatio
})
```

For instance my Android has a device pixel ratio of 3, which makes the canvas the size of just a third of the screen.

Why do you use it? =)

**Comment by mattdesl** [comment]
This is for retina displays, you need higher pixel density to make shapes look crisp, so I scale the canvas and then in the draw loop, I use ctx.scale() and ctx.restore(). Check the demo for an example. :)

PS - sometimes I like to clamp the devicePixelRatio since 2x scale looks pretty good on most devices and will perform better

**Comment by kimasendorf** [comment]
Ah, okay. I just checked the demo.es6. Makes sense =)

But how about a webgl-context? It has no save or scale function.

**Comment by mattdesl** [comment]
In WebGL you will still have to scale everything – for e.g. if you use an OrthographicCamera to make a 20x20 pixel rectangle, you should really make it 60x60 pixels large with a devicePixelRatio of 3.0.

However most engines (like ThreeJS) will support this for you, so you really just need to think in 1x scale, and let the engine handle the device scaling for you. e.g.

```js
threeJSRenderer.setPixelRatio(window.devicePixelRatio);
```

**Comment by kimasendorf** [comment]
All right =) Basically I am just coming from ThreeJS and I've never thought about scaling. I mean I have used upscaled FBOs in Processing. However, just made some tests with scaling but my shaders are already a little intense.
Thanks a lot for your time! Best K
